# Generated by Django 5.0.7 on 2024-12-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="is_staff",
            new_name="is_verified",
        ),
    ]
