# Generated by Django 5.0.7 on 2025-03-22 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("student", "0001_initial"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesheet",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="teacher.subject",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="student_groups", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled_students", to="teacher.subject"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="student_permissions", to="auth.permission"
            ),
        ),
        migrations.AddField(
            model_name="attendancesheet",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="student.student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancesheet",
            unique_together={("subject", "student", "date_time")},
        ),
    ]
