# Generated by Django 5.0.7 on 2024-12-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_rename_is_staff_student_is_verified"),
        ("teacher", "0002_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="enrolled_students", to="teacher.subject"
            ),
        ),
    ]
