# Generated by Django 5.0.7 on 2024-12-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="current_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
